apiVersion: v1
kind: Service
metadata:
  name: fileupload-svc
  labels:
      app: fileupload
spec:
  type: ClusterIP
  ports:
  - port: 9002
    targetPort: 9002
    protocol: TCP
    name: http
  selector:
     app: fileupload
